import { describe, it, expect } from 'vitest'
import { validateEntry } from '../../../frontend/js/utils/bib-validate'

const article = { type: 'article', id: 'k1', fields: {} }

describe('bib-validate (Check button, pure)', () => {
  it('flags every empty standalone required field (existing entry)', () => {
    // id empty -> id-required; all required fields empty -> required-missing
    const res = validateEntry({ type: 'article', id: '', fields: {} }, 'existing')
    expect(res.valid).toBe(false)
    expect(res.byField.id.kind).toBe('id-required')
    expect(res.byField.author.kind).toBe('required-missing')
    expect(res.byField.title.kind).toBe('required-missing')
    expect(res.byField.journal.kind).toBe('required-missing')
    expect(res.byField.year.kind).toBe('required-missing')
  })

  it('OR-group: message attached to EVERY empty member (book: author|editor)', () => {
    // book requires ["author","editor"], title, publisher, year
    const res = validateEntry({ type: 'book', id: 'b1', fields: {} }, 'existing')
    const a = res.byField.author
    const e = res.byField.editor
    expect(a).toMatchObject({ kind: 'required-missing', group: true })
    expect(e).toMatchObject({ kind: 'required-missing', group: true })
    expect(a.labelFields.sort()).toEqual(['author', 'editor'])
    expect(e.labelFields).toEqual(a.labelFields)
  })

  it('OR-group: filling ANY member clears the message from BOTH (reviewer rule)', () => {
    const res = validateEntry(
      { type: 'book', id: 'b1', fields: { author: 'Someone' } },
      'existing'
    )
    expect(res.byField.author).toBeUndefined()
    expect(res.byField.editor).toBeUndefined()
    // the remaining requireds are still flagged
    expect(res.byField.title.kind).toBe('required-missing')
  })

  it('inbook chapter/pages OR-group behaves the same', () => {
    const inbook = {
      type: 'inbook',
      id: 'i1',
      fields: { author: 'A', title: 'T', publisher: 'P', year: '2000' },
    }
    const res = validateEntry(inbook, 'existing')
    expect(res.byField.chapter).toMatchObject({ kind: 'required-missing', group: true })
    expect(res.byField.pages).toMatchObject({ kind: 'required-missing', group: true })
    // one of the two satisfies the group
    const onlyPages = { ...inbook, fields: { ...inbook.fields, pages: '1-10' } }
    const res2 = validateEntry(onlyPages, 'existing')
    expect(res2.byField.chapter).toBeUndefined()
    expect(res2.byField.pages).toBeUndefined()
  })

  it('misc is valid with only a key (no required fields — btxdoc)', () => {
    const res = validateEntry({ type: 'misc', id: 'm1', fields: {} }, 'existing')
    expect(res.valid).toBe(true)
  })

  it('new entry: citation key is NOT required (autogenerated at materialize)', () => {
    const res = validateEntry({ type: 'article', id: '', fields: {} }, 'new')
    expect(res.byField.id).toBeUndefined()
    const resTyped = validateEntry({ type: 'article', id: 'ok', fields: {} }, 'new')
    expect(resTyped.byField.id).toBeUndefined()
  })

  it('rejects invalid citation key characters', () => {
    const res = validateEntry({ type: 'misc', id: 'bad key&', fields: {} }, 'existing')
    expect(res.byField.id.kind).toBe('id-invalid')
  })

  it('validates year, DOI and URL formats for filled values', () => {
    const res = validateEntry(
      { type: 'article', id: 'a1', fields: { author: 'A', title: 'T', journal: 'J', year: '20x1' } },
      'existing'
    )
    expect(res.byField.year.kind).toBe('year-format')
    const resD = validateEntry({ type: 'misc', id: 'm', fields: { doi: '10.abc/123' } }, 'new')
    expect(resD.byField.doi.kind).toBe('doi-format')
    const resU = validateEntry({ type: 'misc', id: 'm', fields: { url: 'not a url' } }, 'new')
    expect(resU.byField.url.kind).toBe('url-invalid')
    const resOk = validateEntry(
      { type: 'misc', id: 'm', fields: { doi: '10.1000/abc123', url: 'https://x.org/a' } },
      'new'
    )
    expect(resOk.valid).toBe(true)
  })

  it('a valid full article passes', () => {
    const res = validateEntry(
      {
        type: 'article',
        id: 'smith2024',
        fields: { author: 'Smith, John', title: 'T', journal: 'J', year: '2024' },
      },
      'existing'
    )
    expect(res.valid).toBe(true)
  })
})
